name: Run Tests with Input Files

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8

      - name: Run script with input files
        run: |
          python Códigos/__main__.py Códigos/ArquivosTXT/input1.txt Códigos/ArquivosTXT/output1.txt
          python Códigos/__main__.py Códigos/ArquivosTXT/input2.txt Códigos/ArquivosTXT/output2.txt
          python Códigos/__main__.py Códigos/ArquivosTXT/input3.txt Códigos/ArquivosTXT/output3.txt

      - name: Upload output files as artifacts
        uses: actions/upload-artifact@v4 
        with:
          name: output-files
          path: Códigos/output*.txt

  lint:
    name: Run Black and Flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          pip install black flake8
      
      - name: Run Black
        run: black --check .
      
      - name: Run Flake8
        run: flake8 .
